[vars]
stage_endpoint = "www.phonepe.com"

[provider.stage_token]


[commands.drove]
run = "drove -e #stage_endpoint -insecure -auth #stage_token"

[template.java-microservice]
vars = { JAVA_HOME = "$JAVA_21" }

[template.java-testng]
vars = { JAVA_HOME = "$JAVA_17" }
